### PR TITLE
Add a Gitter chat badge to README.md

### PR DESCRIPTION
**Pull request by gitter-badger**
### mrkno/Kassy now has a Chat Room on Gitter

@mrkno has just created a chat room. You can visit it here: [https://gitter.im/mrkno/Kassy](https://gitter.im/mrkno/Kassy?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.md:

[Gitter](https://gitter.im/mrkno/Kassy?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

If my aim is a little off, please [let me know](https://github.com/gitterHQ/readme-badger/issues).

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by mrkno** [comment]
@Awarua- thoughts?

**Comment by Awarua-** [comment]
I suppose if this project get real traction then it would be good to have a public discussion forum.
I just look at it like another platform that's going to send me notifications :disappointed:

**Comment by mrkno** [comment]
It just wants to add a badge, you don't have to participate (the only reason it is asking was that I was testing a hubot adapter with gitter)

**Comment by Awarua-** [comment]
Approved

**Comment by mrkno** [comment]
It ties us to one platform + we would need to rename the chat room later.

Do this kind of thing after we have migrated to an organization.

**Pull request closed without merging**
